config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'homes#top'
  get "/home/about" => "homes#about"

  resources :users
  resources :books



 end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

    belongs_to :user

    validates :title, presence: true
    validates :body, presence: true
    validates :body, length: { maximum: 200 }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy

  attachment :profile_image

  validates:name, uniqueness: true
  validates :name, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top, :about]

  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(@user.id)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end


end

app/controllers/books_controller.rb
class BooksController < ApplicationController

def index
  @books=Book.all
  # index画面に投稿フォームがあるから↓
  @book=Book.new
  # current_userでログインしている人を判断している↓
  @user=current_user
end

def create
  @book=Book.new(book_params)
  @book.user_id = current_user.id
  if @book.save
    redirect_to book_path(@book.id), notice: 'You have created book successfully.'
  else
    @books=Book.all
    @user=current_user
    render :index
  end
end

def show
  @book=Book.new
  @books=Book.find(params[:id])
  @user=User.find_by(id: @books.user_id)
end

def edit
  @book=Book.find(params[:id])
  if @book.user == current_user
    render :edit
  else
    redirect_to books_path
  end
end

def update
  @book=Book.find(params[:id])
  if @book.update(book_params)
    redirect_to book_path(@book.id), notice: 'You have updated book successfully.'
  else
    render :edit
  end
end

def destroy
  @book=Book.find(params[:id])
  @book.destroy
  redirect_to books_path
end




  private

  def book_params
    params.require(:book).permit(:title, :body)
  end


end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  
  def top
  end
  
  def about
  end
  
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user=User.find(params[:id])
    @books=@user.books
    # @books=@user.books.page(params[:page]).reverse_order
    # 新しいのが上になる↑
    @book=Book.new
  end

  def index
    @users=User.all
    @user=current_user
    @book=Book.new
  end


  def edit
    @user=User.find(params[:id])
    if @user == current_user
      render :edit
    else
      redirect_to user_path(current_user)
    end
  end

  def update
    @user=User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: 'You have updated user successfully.'
    else
      render :edit
    end
  end


 private
 def user_params
   params.require(:user).permit(:name, :introduction, :profile_image)
 end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this obj from being saved:
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>

<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
<h1>Editing Book</h1>

<%= form_with model:@book,local:true do |f| %>
<div class="form-group">
  <label for="book_title">Title</label>
  <%= f.text_field :title %>
</div>

<div class="form-group">
  <label for="book_opinion">Opinion</label>
  <%= f.text_area :body %>
</div>

<div class="form-group">
<%= f.submit "Update Book" %>
</div>

<%end%>

<%= link_to "Show", book_path(@book.id) %>
|
<%= link_to "Back", books_path %>
    
    </div>
  </div>
</div>

app/views/books/index.html.erb
<p><% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this obj from being saved:
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>
</p>
<div class="container px-5 px-sm-0">
  <div class="row">

    <%= render 'shared/template', book: @book, user: @user %>

    <div class="col-md-8 offset-md-1">
       <h2>Books</h2>

       <table class="table table-hover table-inverse">

         <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
         </tr>
        </thead>

        <tbody>
          <% @books.each do |book| %>
          <tr>
            <td><%= link_to user_path(book.user.id) do %>
              <%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg", size: "40x40" %>
              <%end%>
            </td>
            <td><%= link_to book.title, book_path(book.id) %></td>
            <td><%= book.body %></td>
         </tr>
         <%end%>
        </tbody>

       </table>

    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">

    <%= render 'shared/template', book: @book, user: @user %>

    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>

      <table class="table">
        <tbody>
          <tr>
            <td><%= link_to user_path(@books.user) do %>
              <%= attachment_image_tag @books.user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg", size: "40x40" %>
              <%=@books.user.name%>
              <%end%>
            </td>
            <td><%= link_to @books.title, book_path(@books.id) %></td>
            <td><%= @books.body %></td>

            <% if @books.user == current_user %>
            <td><%= link_to "Edit", edit_book_path, method: :get %></td>
            <td><%= link_to "Destroy", book_path(@books), method: :delete %></td>
            <% end %>

          </tr>
        </tbody>
      </table>

    </div>
  </div>
</div>

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">
      Welcome to
      <i class="fas fa-book"></i>
      <strong>Bookers</strong>
      !</h1>
  </div>
</div>

app/views/homes/top.html.erb
 <% flash.each do |key, value| %>
 <%= content_tag :div, value, class: key %>
 <%end%>

<div class="container">
 <div class="row">
  <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">

   <h1>welcome to
   <i class="fas fa-book"></i>
   <strong>Bookers</strong>
   !!</h1>

   <p>In
   <i class="fas fa-book"></i>
   <strong>Bookers</strong>
   ,</p>

   <p>you can share and exchange your opinions , inpressions , and emotions</p>

   <p>about various books!</p>

   <%= link_to "Log in", new_user_session_path, class:"btn btn-info btn-sm btn-block mb-3 sign_in" %>

   <%= link_to "Sign up", new_user_registration_path, method: :get, class:"btn btn-success btn-sm btn-block sign_up" %>

  </div>
 </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <script src="https://kit.fontawesome.com/91d36909a5.js" crossorigin="anonymous"></script>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/">
            <span>Bookers</span>
          </a>


          <div class="collpse navbar-collapse">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>

            <li>
              <%= link_to user_path(current_user.id) do %>
              <i class="fas fa-home nav-link text-light">Home</i>
              <%end%>
            </li>

            <li>
              <a class="fas fa-users nav-link text-light" href="/users">Users</a>
            </li>

            <li>
              <a class="fas fa-book-open nav-link text-light" href="/books">Books</a>
            </li>

            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
              <i class="fas fa-sign-out-alt nav-link text-light">Log out</i>
              <%end%>
            </li>

            <% else %>
            <li>
              <a class="fas fa-home nav-link text-light" href="/">Home</a>
            </li>

            <li>
              <a class="fas fa-link nav-link text-light" href="/home/about">About</a>
            </li>

            <li>
              <%= link_to new_user_registration_path do %>
              <i class="fas fa-user-plus nav-link text-light">Sign up</i>
              <%end%>
            </li>

            <li>
              <%= link_to new_user_session_path do %>
              <i class="fas fa-sign-in-alt nav-link text-light">Log in</i>
              <%end%>
            </li>

            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>





    <%= yield %>
    <footer>
      <p>CopyRight Infratop.inc</p>

    </footer>
  </body>
</html>

app/views/shared/_template.html.erb
<div class="col-md-3">
 
 <% flash.each do |key, value| %>
 <%= content_tag :div, value, class: key %>
 <%end%>
 
 <h2>User info</h2>

 <%= attachment_image_tag user, :profile_image, :fill, 63, 63, format: 'jpeg', fallback: "no_image.jpg", size: "63x63" %>

  <table class="table">
   <tbody>
    <tr></tr>
    <tr>
     <th>name</th>
     <th><%= user.name %></th>
    </tr>
    <tr>
     <th>introduction</th>
     <th><%= user.introduction %></th>
    </tr>
   </tbody>
  </table>

  <giv class="row">
    <%= link_to edit_user_path(user.id) do %>
    <i class="fas fa-user-cog"></i>
    <%end%>
  </giv>

  <h2 class="mt-3">New book</h2>

  <%= form_with model:book, local:true do |f| %>

  <div class="form-group">
    <label for="book_title">Title</label>
    <%= f.text_field :title %>
  </div>

  <div class="form-group">
    <label for="book_opinion">Opinion</label>
    <%= f.text_area :body %>
  </div>

  <div class="form-group">
    <%= f.submit 'Create Book' %>
  </div>

  <%end%>

</div>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
  <%= @user.errors.count %>errors prohibited this obj from being saved:
  <% @user.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>

<h2>User info</h2>

<%= form_with model: @user, local:true do |f| %>

<label for>Name</label>
<%= f.text_field :name %>

<label for>Image</label>
<%= f.attachment_field :profile_image %>

<label for>Introduction</label>
<%= f.text_area :introduction %>

<%= f.submit 'Update User' %>

<%end%>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">

    <%= render 'shared/template', book: @book, user: @user %>

    <div class="col-md-8 offset-md-1">

      <h2>Users</h2>

      <table class="table">

        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @users.each do |user|%>
          <tr>
            <td><%= attachment_image_tag user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg", size: "40x40" %></td>
            <td><%= user.name %></td>
            <td><%= link_to "Show", user_path(user.id) %></td>
          </tr>
          <%end%>
        </tbody>

      </table>

    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">

    <%= render 'shared/template', book: @book, user: @user %>

    <div class="col-md-8 offset-md-1">

      <h2>Books</h2>

      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @books.each do |book| %>
          <tr>
            <td><%= link_to user_path(book.user) do %>
                <%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg", size: "40x40" %>
                <%end%>
            </td>
            <td><%= link_to book.title, book_path(book.id) %></td>
            <td><%= book.body %></td>
          </tr>
          <%end%>
        </tbody>
      </table>

    </div>
  </div>
</div>